services:
  agent-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      # Optional: override model here if not in .env
      # - LLM_MODEL=gpt-4o-mini
    volumes:
      - ./:/app
    command: [
      "streamlit", "run", "05_GenAI/langgraph_agent/ui_streamlit.py",
      "--server.port", "8501", "--server.address", "0.0.0.0"
    ]

